name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # No tests, just deploy
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.0.8
      with:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: stefan 
        REMOTE_PORT: 22
        SOURCE: .
        TARGET: /home/stefan/yuna-bot
