name: Python application

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # No tests, just deploy
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        username: stefan
        script: cd ~/president-yuna && git pull
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        username: stefan
        script: ~/president-yuna/venv/bin/pip3 install -r ~/president-yuna/requirements.txt
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: ${{ secrets.REMOTE_HOST }}
        key: ${{ secrets.PRIVATE_KEY }}
        username: stefan\
        script: chmod +x ~/president-yuna/start-yuna.sh
        
      
